version: "3"
services:
  fetcher:
    build:
      context: .
    ports:
      - 5286:5286
    environment:
      - MONGODB__CONNECTIONSTRING="mongodb://${MONGO_USER}:${MONGO_PW}@mongodb:27017"
    depends_on:
      - rabbitmq
      - mongo
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
  mongoexpress:
    image: mongo-express:latest
    container_name: mongoexpress
    ports:
      - "8084:8081"
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://${MONGO_USER}:${MONGO_PW}@mongodb:27017"
    restart: always
    depends_on:
      - mongo
volumes:
  mongodata:
