{
 "title": "HnFetcher",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hn_fetcher_api_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Requests by Resource Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "hn_fetcher_api_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "httpclient_requests_sent_total", "legendFormat": "__auto" }
   ]
  }
 ]
}